.TH "level_t" 3 "Vendredi 10 Juin 2022" "Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
level_t \- Créer la structure \fBLevel\fP qui permet de spécifier un niveau en entier\&. Spécifie la construction de la map (tout les blocs présent et où ils se trouvent) Spécifie aussi la liste des coups jouées sous la forme d'une liste chainée\&. Spécifie enfin le numéro du niveau, la largeur du niveau, la hauteur du niveau, si le niveau a était résolu ou non, l'index du maillon ou se trouve le joueur dans la liste chainée map et les coordonnées x et y du joueur dans le niveau\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SH "Description détaillée"
.PP 
Créer la structure \fBLevel\fP qui permet de spécifier un niveau en entier\&. Spécifie la construction de la map (tout les blocs présent et où ils se trouvent) Spécifie aussi la liste des coups jouées sous la forme d'une liste chainée\&. Spécifie enfin le numéro du niveau, la largeur du niveau, la hauteur du niveau, si le niveau a était résolu ou non, l'index du maillon ou se trouve le joueur dans la liste chainée map et les coordonnées x et y du joueur dans le niveau\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sokoban à partir du code source\&.
