.TH "Level" 3 "Vendredi 10 Juin 2022" "Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Level
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structures\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBliste_double\fP * \fBmap\fP"
.br
.RI "liste formant la map "
.ti -1c
.RI "\fBliste_double\fP * \fBcoups\fP"
.br
.RI "pile de coups "
.ti -1c
.RI "bool \fBsolved\fP"
.br
.ti -1c
.RI "unsigned int \fBlvl_number\fP"
.br
.ti -1c
.RI "unsigned int \fBlargeur\fP"
.br
.ti -1c
.RI "unsigned int \fBhauteur\fP"
.br
.ti -1c
.RI "unsigned int \fBindex\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "\fBliste_double\fP* Level::map"

.PP
liste formant la map 
.SS "\fBliste_double\fP* Level::coups"

.PP
pile de coups 
.SS "bool Level::solved"

.SS "unsigned int Level::lvl_number"

.SS "unsigned int Level::largeur"

.SS "unsigned int Level::hauteur"

.SS "unsigned int Level::index"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sokoban à partir du code source\&.
