.TH "src/runtime.h" 3 "Vendredi 10 Juin 2022" "Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/runtime.h
.SH SYNOPSIS
.br
.PP
\fC#include <SDL2/SDL\&.h>\fP
.br
\fC#include <SDL2/SDL_image\&.h>\fP
.br
\fC#include <SDL2/SDL_mixer\&.h>\fP
.br
\fC#include <SDL2/SDL_ttf\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'structures\&.h'\fP
.br

.SS "Structures de données"

.in +1c
.ti -1c
.RI "struct \fBruntime_s\fP"
.br
.RI "structure qui stock tout ce qui fait parti de l'affichage "
.in -1c
.SS "Définitions de type"

.in +1c
.ti -1c
.RI "typedef struct \fBruntime_s\fP \fBruntime_t\fP"
.br
.RI "structure qui stock tout ce qui fait parti de l'affichage "
.in -1c
.SH "Documentation des définitions de type"
.PP 
.SS "typedef struct \fBruntime_s\fP \fBruntime_t\fP"

.PP
structure qui stock tout ce qui fait parti de l'affichage 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Sokoban à partir du code source\&.
